# Generated by Django 3.2 on 2023-03-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_title_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('title', 'author'), name='unique_review'),
        ),
    ]
